In [2]:
# '''
# https://gym.openai.com/docs/
# '''
'''
git clone https://github.com/openai/gym.git
cd gym
pip install -e .

import sys
sys.path.append("/Users/xli27/GitHub/gym")

conda install -c conda-forge pyglet
'''
import sys
sys.path.append("/Users/xli27/GitHub/gym")
import gym
import numpy as np

In [3]:

env = gym.make("MountainCar-v0")
env = env.unwrapped

# env.reset()

LEARNING_RATE = 0.1
DISCOUNT = 0.95
EPISODES = 2000

EPSILON = 0.86
START_EPISILON_DECAYING = 1
END_EPISOLON_DECAYING = EPISODES // 2

epsilon_decay_value = EPSILON / (END_EPISOLON_DECAYING - START_EPISILON_DECAYING)

# print(env.observation_space.high)
# print(env.observation_space.low)
# print(env.action_space.n)

SHOW_EVERY = 500

DISCRETE_OS_SIZE = [20] * len(env.observation_space.high)
DISCRETE_OS_WIN_SIZE = (env.observation_space.high - env.observation_space.low) / DISCRETE_OS_SIZE

# print(DISCRETE_OS_SIZE)
# print(DISCRETE_OS_WIN_SIZE)

q_table = np.random.uniform(low=-2, high=0, size=(DISCRETE_OS_SIZE) + [env.action_space.n])

# print(q_table.shape)

def get_discrete_state(state):
    discrete_state = (state - env.observation_space.low) / DISCRETE_OS_WIN_SIZE
    return tuple(discrete_state.astype(np.int))

for episode in range(EPISODES):
#     if episode % SHOW_EVERY == 0:
#         print(episode)
#         render = True        
#     else:
    render = False

    discrete_state = get_discrete_state(env.reset())
    done = False
    while not done:
        if np.random.random() > EPSILON:
            action = np.argmax(q_table[discrete_state])
        else:
            action = np.random.randint(0, env.action_space.n)

        new_state, reward, done, _ =  env.step(action)
        new_discrete_state = get_discrete_state(new_state)
        # print(reward, new_state)
        
        if (render):
            env.render()
        if not done:
            max_future_q = np.max(q_table[discrete_state])
            current_q = q_table[discrete_state + (action,)]

            new_q = (1 - LEARNING_RATE) * current_q + LEARNING_RATE * (reward + DISCOUNT * max_future_q)
            q_table[discrete_state + (action, )] = new_q
        elif new_state[0] >= env.goal_position:
            print(f"We made it on episode {episode}")
            q_table[discrete_state + (action,)] = 0

        discrete_state = new_discrete_state

    if END_EPISOLON_DECAYING >= episode >= START_EPISILON_DECAYING:
        EPSILON -= epsilon_decay_value
        
env.close()


/Users/xli27/GitHub/gym/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


We made it on episode 0
We made it on episode 1
We made it on episode 2
We made it on episode 3
We made it on episode 4
We made it on episode 5
We made it on episode 6
We made it on episode 7
We made it on episode 8
We made it on episode 9
We made it on episode 10
We made it on episode 11
We made it on episode 12
We made it on episode 13
We made it on episode 14
We made it on episode 15
We made it on episode 16
We made it on episode 17
We made it on episode 18
We made it on episode 19
We made it on episode 20
We made it on episode 21
We made it on episode 22
We made it on episode 23
We made it on episode 24
We made it on episode 25
We made it on episode 26
We made it on episode 27
We made it on episode 28
We made it on episode 29
We made it on episode 30
We made it on episode 31
We made it on episode 32
We made it on episode 33
We made it on episode 34
We made it on episode 35
We made it on episode 36
We made it on episode 37
We made it on episode 38
We made it on episode 39
We made it

KeyboardInterrupt: 

In [10]:
alist = [20]
blist = alist *2
print(blist)

[20, 20]


In [11]:
clist = blist + [3]
print (clist)

[20, 20, 3]


In [12]:
dlist = (blist) + [3]
print (dlist)

[20, 20, 3]


In [15]:
dlist[0,0,0] = 4
dlist[19,19,2] = 10
print(dlist)

TypeError: list indices must be integers or slices, not tuple

In [1]:
import numpy as np

q_table = np.random.uniform(low=-2, high=0, size=([20,20]) + [3])
#
# 
print(q_table)

ModuleNotFoundError: No module named 'numpy'

In [4]:
print(q_table)

[[[-0.10450358 -0.77915317 -1.86907632]
  [-1.91738549 -1.82001761 -0.21738222]
  [-0.13283234 -0.82746608 -1.450892  ]
  ...
  [-0.25848499 -1.69722676 -1.23464044]
  [-0.95107677 -0.98195617 -0.60854579]
  [-0.53195624 -1.2093379  -0.80192951]]

 [[-0.41388732 -0.27354855 -0.88402988]
  [-0.98883519 -1.32435377 -0.46243407]
  [-2.03265721 -1.86427455 -1.60823691]
  ...
  [-1.45081617 -1.31595798 -0.19813907]
  [-0.80457577 -1.3093039  -1.48683896]
  [-1.82367498 -0.08453727 -1.37113415]]

 [[-0.67661716 -1.2652637  -0.98383909]
  [-1.1765008  -1.9698213  -0.45655986]
  [-5.51487444 -5.69941699 -5.28199387]
  ...
  [-1.74133739 -0.62366264 -1.43160585]
  [-0.07473881 -1.42584271 -0.95300503]
  [-1.26394851 -1.0158637  -0.47187504]]

 ...

 [[-0.47642137 -1.38286807 -0.80616345]
  [-0.95008482 -0.27915659 -0.00877287]
  [-0.75038739 -0.65909699 -1.5667922 ]
  ...
  [-1.37283855 -0.21728338 -0.09989575]
  [-1.39560165 -1.83948528 -0.56471487]
  [-1.72799057 -1.92268377 -1.74897844]]

 [