In [1]:
import sys
sys.path.append("/Users/xli27/GitHub/gym")
import gym
import numpy as np


In [73]:
env = gym.make("MountainCar-v0")
env = env.unwrapped

env.reset()

print(env.observation_space.high) # position and velocity # [0.6  0.07]
print(env.observation_space.low) # [-1.2  -0.07]
print(env.action_space.sample())
print(env.action_space.n) # 3

DISCRETE_OS_SIZE = [20] * len(env.observation_space.high)
DISCRETE_OS_WIN_SIZE = (env.observation_space.high - env.observation_space.low) / DISCRETE_OS_SIZE

print(DISCRETE_OS_SIZE) # [20, 20]
print(DISCRETE_OS_WIN_SIZE) # [0.09  0.007]

q_table = np.random.uniform(low=-2, high=0, size=(DISCRETE_OS_SIZE) + [env.action_space.n])
#
# 
print(q_table.shape)

def get_discrete_state(state):
    discrete_state = (state - env.observation_space.low) / DISCRETE_OS_WIN_SIZE
    return tuple(discrete_state.astype(np.int))

num_states = (env.observation_space.high - env.observation_space.low)*np.array([10, 100])
num_states = np.round(num_states, 0).astype(int) + 1

print(num_states)

[0.6  0.07]
[-1.2  -0.07]
1
3
[20, 20]
[0.09  0.007]
(20, 20, 3)
[19 15]


In [60]:
ar1 = [10, 10]
ar2 = ar1 * np.array([5, 10])
print (ar2)

[ 50 100]


In [11]:
state = env.reset()
print(state)

[-0.56237947  0.        ]


In [14]:
state_adj = (state - env.observation_space.low)*np.array([10, 100])
state_adj = np.round(state_adj).astype(int)
print(state_adj)

[6 7]


In [66]:
q_table = np.random.uniform(low=-2, high=0, size=([5,6]) + [env.action_space.n])
#
# 
print(q_table)

[[[-0.01490791 -1.67052118 -1.63056951]
  [-0.47108659 -1.13413356 -1.17334944]
  [-1.25643674 -0.49483287 -0.04475732]
  [-0.20708907 -0.8589061  -0.90581963]
  [-1.42376134 -0.33485596 -0.10235303]
  [-0.30834215 -1.4658891  -0.70025855]]

 [[-0.44261857 -1.20145462 -1.85207475]
  [-1.88483115 -1.42219282 -0.72830343]
  [-1.32833082 -1.03305467 -0.033312  ]
  [-1.66973896 -0.43089465 -1.1671716 ]
  [-1.41495049 -0.29379316 -0.8924225 ]
  [-0.20251185 -0.67016834 -1.67901509]]

 [[-1.17680134 -0.83765427 -0.45219272]
  [-1.23262374 -0.55037372 -0.67074304]
  [-0.29480941 -1.94063874 -1.26487921]
  [-0.41035297 -1.66142869 -0.8025219 ]
  [-1.80042158 -1.7041174  -0.40191797]
  [-1.92062189 -0.83439821 -1.99974691]]

 [[-1.09718405 -0.80248835 -1.20169932]
  [-0.50655597 -1.3897882  -0.02816361]
  [-1.89589759 -1.4610533  -0.20859424]
  [-0.08664625 -0.21504449 -0.06526969]
  [-0.2684966  -1.54318601 -1.3846637 ]
  [-1.00437559 -0.27707244 -0.03960747]]

 [[-1.01298251 -1.63314869 -0.81

In [67]:
# action = np.argmax(Q[state_adj[0], state_adj[1]]) 

action = np.argmax(q_table[2,0]) 
print (action) #index

print(np.max(q_table[2,0])) #value

2
-0.4521927234559864


In [48]:
print(q_table[2,2]) 
env.reset()

[-1.48841338 -0.5229928  -0.49726891]


array([-0.40078756,  0.        ])

In [55]:
print(Q)

[[[ 7.15645665e-01 -7.03203823e-01  4.88036505e-02]
  [ 1.98027812e-01  8.51226811e-01  5.72696070e-01]
  [ 4.28417814e-01  8.04822735e-01 -7.16803546e-01]
  [-1.58260955e+00  3.68338785e-01 -2.80494912e+00]
  [-4.57806464e+00 -4.17075552e+00 -5.06263005e+00]
  [-4.62173068e+00 -5.04685311e+00 -4.80404840e+00]
  [-5.21948020e+00 -5.58206172e+00 -5.58905289e+00]
  [-6.83377529e+00 -6.76964009e+00 -6.71801642e+00]
  [-6.36144335e+00 -6.38401392e+00 -6.46735964e+00]
  [-8.78117516e-01 -4.31339141e-01 -4.00401468e-01]
  [-6.02976309e-01 -2.35251363e-01  9.44092796e-01]
  [-3.80457724e-01  1.18319447e-01  6.78841334e-01]
  [ 6.22979938e-01 -3.47256035e-01  2.77781736e-01]
  [ 2.71843809e-02  5.04556128e-02  1.31057254e-01]
  [ 4.45501214e-01 -8.17769132e-01  2.83663600e-01]]

 [[ 8.18798000e-01  2.94044005e-01 -9.69843654e-01]
  [ 1.44932072e-01 -3.43759605e-01  6.98333806e-01]
  [-3.92987280e-01  1.86721543e-01  9.57303349e-01]
  [-3.08895215e+00 -3.34428031e+00 -2.13032784e+00]
  [-4.6935

In [54]:
print(env.step(np.random.randint(0, env.action_space.n)))

(array([-0.41821611, -0.005184  ]), -1.0, False, {})


In [ ]:
env.reset()

num_states = (env.observation_space.high - env.observation_space.low)*np.array([10, 100])
num_states = np.round(num_states, 0).astype(int) + 1 # [19 15]

# Initialize Q table
Q = np.random.uniform(low = -1, high = 1, 
                      size = (num_states[0], num_states[1], 
                              env.action_space.n))
    
# Discretize state
state_adj = (state - env.observation_space.low)*np.array([10, 100])
state_adj = np.round(state_adj, 0).astype(int) ## numpy.around(a, decimals=0, out=None ## like [6 7]

done = False

epsilon = 0.8
learning = 0.2
discount = 0.9

tot_reward, reward = 0,0

# QLearning(env, 0.2, 0.9, 0.8, 0, 5000)

it = 0       
while done != True:   
    # Render environment for last five episodes

    env.render()

    # Determine next action - epsilon greedy strategy
    if np.random.random() < 1 - epsilon:
        action = np.argmax(Q[state_adj[0], state_adj[1]])  ## find the best action
    else:
        action = np.random.randint(0, env.action_space.n)

    # Get next state and reward
    state2, reward, done, info = env.step(action) 
    
#     print('action {}'.format(action))

    # Discretize state2
    state2_adj = (state2 - env.observation_space.low)*np.array([10, 100])
    state2_adj = np.round(state2_adj, 0).astype(int)

    #Allow for terminal states
    if done and state2[0] >= 0.5:
        Q[state_adj[0], state_adj[1], action] = reward

    # Adjust Q value for current state
    else:
        delta = learning*(reward + 
                         discount*np.max(Q[state2_adj[0], 
                                           state2_adj[1]]) - 
                         Q[state_adj[0], state_adj[1],action]) ## update equation
        Q[state_adj[0], state_adj[1],action] += delta ## q-table updated

    # Update variables
    tot_reward += reward
    state_adj = state2_adj
    it += 1
    if (it % 1000 == 0):
        print('it {}, reward {}'.format(it, reward))


it 1000, reward -1.0
it 2000, reward -1.0
it 3000, reward -1.0


ArgumentError: ("argument 1: <class 'RecursionError'>: maximum recursion depth exceeded while calling a Python object", "selector = b'inLiveResize'", "argtypes =[<class 'ctypes.c_void_p'>, <class 'ctypes.c_void_p'>]", "encoding = b'c16@0:8'")

In [ ]:
env.close()

In [63]:
print(env.action_space.sample())

1


In [68]:
print(Q)

[[[ 7.15645665e-01 -7.03203823e-01  4.88036505e-02]
  [ 1.98027812e-01  8.51226811e-01  5.72696070e-01]
  [ 4.28417814e-01  8.04822735e-01 -7.16803546e-01]
  [-1.58260955e+00  3.68338785e-01 -2.80494912e+00]
  [-4.57806464e+00 -4.17075552e+00 -5.06263005e+00]
  [-4.62173068e+00 -5.04685311e+00 -4.80404840e+00]
  [-5.21948020e+00 -5.58206172e+00 -5.58905289e+00]
  [-6.83377529e+00 -6.76964009e+00 -6.71801642e+00]
  [-6.36144335e+00 -6.38401392e+00 -6.46735964e+00]
  [-8.78117516e-01 -4.31339141e-01 -4.00401468e-01]
  [-6.02976309e-01 -2.35251363e-01  9.44092796e-01]
  [-3.80457724e-01  1.18319447e-01  6.78841334e-01]
  [ 6.22979938e-01 -3.47256035e-01  2.77781736e-01]
  [ 2.71843809e-02  5.04556128e-02  1.31057254e-01]
  [ 4.45501214e-01 -8.17769132e-01  2.83663600e-01]]

 [[ 8.18798000e-01  2.94044005e-01 -9.69843654e-01]
  [ 1.44932072e-01 -3.43759605e-01  6.98333806e-01]
  [-3.92987280e-01  1.86721543e-01  9.57303349e-01]
  [-3.08895215e+00 -3.34428031e+00 -2.13032784e+00]
  [-4.6935

In [70]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break


[-0.03765016 -0.03096156  0.0025768  -0.03535571]
[-0.03826939 -0.22612036  0.00186968  0.25813911]
[-0.0427918  -0.42126896  0.00703247  0.55141118]
[-0.05121718 -0.61648897  0.01806069  0.84630148]
[-0.06354696 -0.8118526   0.03498672  1.14460869]
[-0.07978401 -1.00741368  0.05787889  1.44805479]
[-0.09993229 -1.20319757  0.08683999  1.75824576]
[-0.12399624 -1.39918923  0.1220049   2.07662431]
[-0.15198002 -1.20549759  0.16353739  1.82402704]
[-0.17608997 -1.40201369  0.20001793  2.16273415]
Episode finished after 10 timesteps
[-0.04137723  0.01923208 -0.01866117 -0.01833391]
[-0.04099259  0.21461661 -0.01902785 -0.31684575]
[-0.03670026  0.01977078 -0.02536476 -0.03022376]
[-0.03630484  0.21524712 -0.02596924 -0.33080039]
[-0.0319999   0.02050427 -0.03258524 -0.04641871]
[-0.03158981  0.21607795 -0.03351362 -0.34920187]
[-0.02726825  0.02144828 -0.04049766 -0.06727246]
[-0.02683929 -0.17307036 -0.04184311  0.21236321]
[-0.0303007   0.02262409 -0.03759584 -0.09321981]
[-0.02984821  

[-0.00442384  0.33427439  0.04789127 -0.26193435]
[ 0.00226165  0.52868117  0.04265258 -0.5391355 ]
[ 0.01283527  0.33298638  0.03186987 -0.23332424]
[ 0.019495    0.52763881  0.02720339 -0.51578647]
[ 0.03004778  0.72236734  0.01688766 -0.79977437]
[ 0.04449512  0.52701785  0.00089217 -0.50182719]
[ 0.05503548  0.33188334 -0.00914437 -0.20886324]
[ 0.06167315  0.13689333 -0.01332164  0.08092114]
[ 0.06441101 -0.05803515 -0.01170322  0.36937146]
[ 0.06325031  0.13725111 -0.00431579  0.07302146]
[ 0.06599533 -0.0578087  -0.00285536  0.36433962]
[0.06483916 0.13735372 0.00443143 0.07075772]
[ 0.06758623  0.33241186  0.00584659 -0.22052378]
[ 0.07423447  0.52744975  0.00143611 -0.51135673]
[ 0.08478346  0.3323076  -0.00879102 -0.21822159]
[ 0.09142962  0.52755411 -0.01315545 -0.51366456]
[ 0.1019807   0.33261988 -0.02342874 -0.22515612]
[ 0.1086331   0.13784048 -0.02793187  0.06004538]
[ 0.11138991 -0.05687009 -0.02673096  0.3437864 ]
[ 0.1102525   0.13862174 -0.01985523  0.04279545]
[ 0.

[-0.02518636 -0.82334817  0.03436742  1.09277679]
[-0.04165333 -1.01890569  0.05622296  1.39604188]
[-0.06203144 -1.21468018  0.0841438   1.70576045]
[-0.08632504 -1.41066332  0.118259    2.02340418]
[-0.11453831 -1.60679448  0.15872709  2.35023328]
[-0.1466742  -1.80294442  0.20573175  2.68722963]
Episode finished after 14 timesteps
[-0.04174202  0.0330575  -0.03817968 -0.03075822]
[-0.04108087 -0.16149673 -0.03879484  0.24963835]
[-0.0443108  -0.35604381 -0.03380207  0.52983657]
[-0.05143168 -0.55067435 -0.02320534  0.81167969]
[-0.06244516 -0.74547086 -0.00697175  1.09697403]
[-0.07735458 -0.94050032  0.01496773  1.38746144]
[-0.09616459 -0.74556808  0.04271696  1.09949618]
[-0.11107595 -0.94122544  0.06470688  1.40526946]
[-0.12990046 -1.13708829  0.09281227  1.71745945]
[-0.15264222 -0.94314496  0.12716146  1.45504419]
[-0.17150512 -1.13957789  0.15626235  1.78459934]
[-0.19429668 -0.94651925  0.19195433  1.54429415]
Episode finished after 12 timesteps
[ 0.00170043 -0.01020984  0.

In [71]:
env.close()